In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

print(torch.__version__)

2.0.0


In [3]:
scalar = torch.tensor(5) # single value
scalar

tensor(5)

In [4]:
vector = torch.tensor([1, 2, 3]) # 1D array
vector

tensor([1, 2, 3])

In [5]:
MATRIX = torch.tensor([[1,2], [3,4], [5, 6]]) # 2D array (matrix and tensor are capital, scalar and vector are lower)
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
TENSOR = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 0, 1, 2], [1, 2, 3, 4]]]) # n-D array (must have same amount of items in the arrays)
TENSOR

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[9, 0, 1, 2],
         [1, 2, 3, 4]]])

In [7]:
random = torch.rand(3, 4)
random

tensor([[0.9509, 0.5184, 0.5088, 0.7324],
        [0.6611, 0.9871, 0.3708, 0.9762],
        [0.9839, 0.1377, 0.0922, 0.9966]])

In [8]:
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
random_range = torch.arange(2, 15, step=3)
random_range

tensor([ 2,  5,  8, 11, 14])

In [11]:
random_range = torch.arange(15, 2, step=-3)
random_range

tensor([15, 12,  9,  6,  3])

In [12]:
random_range = torch.arange(2,6)
zeros = torch.zeros_like(random_range)
zeros

tensor([0, 0, 0, 0])

In [13]:
tensor = torch.tensor([1,2,3], dtype=torch.float16, device=None, requires_grad=False)
# by default, float32 will be used
# device means CPU or GPU (if we interact 2 tensors with each other, and one lives in the GPU and the other in the CPU, then error)
# required grad means whether we track gradients
tensor.type(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [14]:
tensorA = torch.tensor([1,2,3])
tensorB = torch.tensor([2,2,1])

res = torch.matmul(tensorA, tensorB) # dot product, matrix multiplication
res

tensor(9)

In [15]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = torch.matmul(a, b)

# a[0][0] * b[0][0] + a[0][1] * b[1][0] 1*5 + 2*7 // 19
# a[0][0] * b[0][1] + a[0][1] * b[1][1] 1*6 + 2*8 // 22

# a[1][0] * b[0][0] + a[1][1] * b[1][0] 3*5 + 4*7 // 43
# a[1][0] * b[0][1] + a[1][1] * b[1][1] 3*6 + 4*8 // 50

print(c)

tensor([[19, 22],
        [43, 50]])


In [16]:
a = torch.arange(0, 100, 10)
a.min()

tensor(0)

In [17]:
a.max()

tensor(90)

In [18]:
a.type(torch.float32).mean()

tensor(45.)

In [19]:
a[0:2].max()

tensor(10)

In [20]:
a.argmax() # find the position in the tensor (same for argmin)

tensor(9)

In [21]:
a = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [24]:
torch.numel(a)

8

In [28]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
torch.linspace(2, 10, steps=10) 

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])

In [32]:
torch.logspace(2, 10, steps=10) 


tensor([1.0000e+02, 7.7426e+02, 5.9948e+03, 4.6416e+04, 3.5938e+05, 2.7826e+06,
        2.1544e+07, 1.6681e+08, 1.2915e+09, 1.0000e+10])

In [33]:
torch.randperm(10)

tensor([5, 7, 1, 4, 8, 2, 6, 0, 9, 3])

In [36]:
x = torch.arange(0, 10, 2)
y = torch.tensor([2, 3, 4, 5])
torch.cat((x, y))

tensor([0, 2, 4, 6, 8, 2, 3, 4, 5])

In [40]:
x = torch.tensor([[1,2], [3,4], [5,6]])
y = torch.tensor([[7,8], [9,10], [11,12]])
torch.hstack([x,y])

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10],
        [ 5,  6, 11, 12]])

In [41]:
torch.vstack([x,y])

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [44]:
x = torch.tensor([[2,3,4],[5,6,7]])
x.squeeze()

tensor([[2, 3, 4],
        [5, 6, 7]])

In [46]:
x = torch.rand(7, 7)
x.size()

torch.Size([7, 7])