In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

print(torch.__version__)

2.0.0


In [3]:
scalar = torch.tensor(5) # single value
scalar

tensor(5)

In [10]:
vector = torch.tensor([1, 2, 3]) # 1D array
vector

tensor([1, 2, 3])

In [16]:
MATRIX = torch.tensor([[1,2], [3,4], [5, 6]]) # 2D array (matrix and tensor are capital, scalar and vector are lower)
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 0, 1, 2], [1, 2, 3, 4]]]) # n-D array (must have same amount of items in the arrays)
TENSOR

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[9, 0, 1, 2],
         [1, 2, 3, 4]]])

In [18]:
random = torch.rand(3, 4)
random

tensor([[9.0472e-01, 4.3750e-02, 3.0663e-01, 2.7813e-01, 4.5646e-01, 6.9552e-01],
        [8.8572e-01, 5.2905e-01, 3.5212e-01, 3.0188e-01, 4.3760e-01, 9.0888e-01],
        [2.4102e-01, 7.2022e-01, 4.3864e-01, 6.9125e-01, 3.0428e-04, 1.0066e-01]])

In [20]:
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
random_range = torch.arange(2, 15, step=3)
random_range

tensor([ 2,  5,  8, 11, 14])

In [28]:
random_range = torch.arange(15, 2, step=-3)
random_range

tensor([15, 12,  9,  6,  3])

In [29]:
random_range = torch.arange(2,6)
zeros = torch.zeros_like(random_range)
zeros

tensor([0, 0, 0, 0])

In [33]:
tensor = torch.tensor([1,2,3], dtype=torch.float16, device=None, requires_grad=False)
# by default, float32 will be used
# device means CPU or GPU (if we interact 2 tensors with each other, and one lives in the GPU and the other in the CPU, then error)
# required grad means whether we track gradients
tensor.type(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
tensorA = torch.tensor([1,2,3])
tensorB = torch.tensor([2,2,1])

res = torch.matmul(tensorA, tensorB) # dot product, matrix multiplication
res

tensor(9)

In [40]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = torch.matmul(a, b)

# a[0][0] * b[0][0] + a[0][1] * b[1][0] 1*5 + 2*7 // 19
# a[0][0] * b[0][1] + a[0][1] * b[1][1] 1*6 + 2*8 // 22

# a[1][0] * b[0][0] + a[1][1] * b[1][0] 3*5 + 4*7 // 43
# a[1][0] * b[0][1] + a[1][1] * b[1][1] 3*6 + 4*8 // 50

print(c)

tensor([[19, 22],
        [43, 50]])
