In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

print(torch.__version__)

2.0.0


In [3]:
scalar = torch.tensor(5) # single value
scalar

tensor(5)

In [10]:
vector = torch.tensor([1, 2, 3]) # 1D array
vector

tensor([1, 2, 3])

In [16]:
MATRIX = torch.tensor([[1,2], [3,4], [5, 6]]) # 2D array (matrix and tensor are capital, scalar and vector are lower)
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 0, 1, 2], [1, 2, 3, 4]]]) # n-D array (must have same amount of items in the arrays)
TENSOR

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[9, 0, 1, 2],
         [1, 2, 3, 4]]])

In [18]:
random = torch.rand(3, 4)
random

tensor([[9.0472e-01, 4.3750e-02, 3.0663e-01, 2.7813e-01, 4.5646e-01, 6.9552e-01],
        [8.8572e-01, 5.2905e-01, 3.5212e-01, 3.0188e-01, 4.3760e-01, 9.0888e-01],
        [2.4102e-01, 7.2022e-01, 4.3864e-01, 6.9125e-01, 3.0428e-04, 1.0066e-01]])

In [20]:
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
random_range = torch.arange(2, 15, step=3)
random_range

tensor([ 2,  5,  8, 11, 14])

In [28]:
random_range = torch.arange(15, 2, step=-3)
random_range

tensor([15, 12,  9,  6,  3])